# Generated by Django 5.1.3 on 2024-11-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0002_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categorie",
        ),
    ]
