# Generated by Django 5.1.3 on 2024-11-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0003_rename_category_categorie"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categorie",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
